;; R7RS-small chapter 2: lexical conventions.
(import (scheme base) (scheme read) (scheme write) (scheme char)
        (conformance test))

(define (read-from s) (read (open-input-string s)))
(define (read-all s)
  (let ((p (open-input-string s)))
    (let loop ((acc '()))
      (let ((x (read p)))
        (if (eof-object? x) (reverse acc) (loop (cons x acc)))))))
(define (written x)
  (let ((p (open-output-string))) (write x p) (get-output-string p)))

(section "2.1 Identifiers")
(test #t (eq? '|H\x65;llo| 'Hello))
(test #t (eq? '|\x3BB;| (string->symbol (string (integer->char #x3BB)))))
(test #t (eq? '|\t\t| '|\x9;\x9;|))
(test "" (symbol->string '||))
(test #t (symbol? '||))
(test #f (eq? '|| 'a))
(test #t (symbol? '...))
(test #t (symbol? '+))
(test #t (symbol? '+soup+))
(test #t (symbol? '<=?))
(test #t (symbol? '->string))
(test #t (symbol? 'a34kTMNs))
(test #t (symbol? 'lambda))
(test #t (symbol? 'list->vector))
(test #t (symbol? 'q))
(test #t (symbol? 'V17a))
(test "two words" (symbol->string '|two words|))
(test #t (eq? '|two words| '|two\x20;words|))
(test #t (symbol? 'the-word-recursion-has-many-meanings))
(test #t (symbol? '!$%&*/:<=>?^_~))
;; extended identifier characters, each on its own
(test '(! $ % & * + - |.| / : < = > ? @ ^ _ ~)
      (map (lambda (c) (string->symbol (string c))) (string->list "!$%&*+-./:<=>?@^_~")))
;; case is significant
(test #f (eq? 'abc 'ABC))
(test "ABC" (symbol->string 'ABC))
;; case folding directives affect the data read after them
(test 'abc (read-from "#!fold-case ABC"))
(test '(abc ABC) (read-all "#!fold-case ABC #!no-fold-case ABC"))
(test #\A (read-from "#!fold-case #\\A"))
(test #\space (read-from "#!fold-case #\\SPACE"))
(test "ABC" (read-from "#!fold-case \"ABC\""))
;; hex escapes are case-insensitive
(test #t (eq? '|\x41;| '|\X41;|))
(test #t (eq? '|\x6a;| '|\x6A;|))

(section "2.2 Whitespace and comments")
(test '(1 2 3) (read-all "1 ; a comment\n2\t3"))
(test '(1 3) (read-all "1 #;2 3"))
(test '(1 4) (read-all "1 #; (2 3) 4"))
(test '(1 4) (read-all "1 #;#;2 3 4"))
(test '(1 2) (read-all "1 #| a #| nested |# comment |# 2"))
(test '(a b) (read-all "a #|x|#b"))
(test '(1 (2 3)) (list 1 (list 2 #;(ignored) 3)))
#| A block comment in the program text,
   #| nested |#
   is whitespace. |#
(define fact
  (lambda (n)
    (if (= n 0)
        #;(= n 1)
        1          ;Base case: return 1
        (* n (fact (- n 1))))))
(test 120 (fact 5))

(section "2.3 Other notations")
(test #t (symbol? (read-from "..")))
(test #t (symbol? (read-from "...")))
(test #t (symbol? (read-from "+a")))
(test #t (symbol? (read-from "-")))
(test #t (symbol? (read-from "+")))
(test '(1 . 2) (read-from "(1 . 2)"))
(test #t #true)
(test #f #false)
(test #t (vector? #(1 2)))
(test #t (bytevector? #u8(1 2)))
(test 10 #xA)
(test 10 #d10)
(test 8 #o10)
(test 2 #b10)
(test #t (exact? #e1.5))
(test #t (inexact? #i3))
(test #\a (read-from "#\\a"))
(test '(quasiquote (a (unquote b) (unquote-splicing c))) (read-from "`(a ,b ,@c)"))
(test '(quote a) (read-from "'a"))

(section "2.4 Datum labels")
(test "#0=(a b c . #0#)"
      (let ((x (list 'a 'b 'c)))
        (set-cdr! (cddr x) x)
        (written x)))
(test #t (let ((x (read-from "#0=(a b . #0#)"))) (eq? x (cddr x))))
(test #t (let ((x (read-from "(#1=(1 2) #1#)"))) (eq? (car x) (cadr x))))
(test '((1 2) (1 2)) (read-from "(#1=(1 2) #1#)"))
(test #t (let ((v (read-from "#0=#(a #0#)"))) (eq? v (vector-ref v 1))))
(test #t (let ((x '(#5=(x) #5#))) (eq? (car x) (cadr x))))

(test-report)
