;; R7RS-small 4.1: primitive expression types.
(import (scheme base) (conformance test))

(section "4.1.1 Variable references")
(define x 28)
(test 28 x)

(section "4.1.2 Literal expressions")
(test 'a (quote a))
(test #(a b c) (quote #(a b c)))
(test '(+ 1 2) (quote (+ 1 2)))
(test 'a 'a)
(test #(a b c) '#(a b c))
(test '() '())
(test '(+ 1 2) '(+ 1 2))
(test '(quote a) '(quote a))
(test '(quote a) ''a)
(test 145932 '145932)
(test 145932 145932)
(test "abc" '"abc")
(test "abc" "abc")
(test #\a '#\a)
(test #\a #\a)
(test #(a 10) '#(a 10))
(test #(a 10) #(a 10))
(test #u8(64 65) '#u8(64 65))
(test #u8(64 65) #u8(64 65))
(test #t '#t)
(test #t #t)

(section "4.1.3 Procedure calls")
(test 7 (+ 3 4))
(test 12 ((if #f + *) 3 4))
(test 3 ((lambda (f) (f 1 2)) +))
;; operator and operands are evaluated with the same rules
(test 5 ((car (list (lambda (x) x))) 5))
(test-values (1 2) (values 1 2))
(test-values () (values))

(section "4.1.4 Procedures")
(test #t (procedure? (lambda (x) (+ x x))))
(test 8 ((lambda (x) (+ x x)) 4))
(define reverse-subtract (lambda (x y) (- y x)))
(test 3 (reverse-subtract 7 10))
(define add4 (let ((x 4)) (lambda (y) (+ x y))))
(test 10 (add4 6))
(test '(3 4 5 6) ((lambda x x) 3 4 5 6))
(test '(5 6) ((lambda (x y . z) z) 3 4 5 6))
(test '() ((lambda (x y . z) z) 3 4))
(test '() ((lambda x x)))
;; rest lists are newly allocated
(test #f (let ((l (list 1 2))) (eq? l (apply (lambda x x) l))))
;; each evaluation of a lambda gives a procedure with its own location
(test #t (let ((p (lambda (x) x))) (eqv? p p)))
;; a body may start with definitions (letrec* semantics)
(test 6 ((lambda () (define a 1) (define (b) (+ a 2)) (+ a (b) 2))))
(test 'body ((lambda () 'body)))

(section "4.1.5 Conditionals")
(test 'yes (if (> 3 2) 'yes 'no))
(test 'no (if (> 2 3) 'yes 'no))
(test 1 (if (> 3 2) (- 3 2) (+ 3 2)))
(test 'true (if '() 'true 'false))
(test 'true (if 0 'true 'false))
(test 'false (if #f 'true 'false))
(test 'only (if #t 'only))

(section "4.1.6 Assignments")
(define y 2)
(test 3 (+ y 1))
(set! y 4)
(test 5 (+ y 1))
(test 10 (let ((z 1)) (set! z 10) z))
(test '(2 2) (let* ((z 1) (f (lambda () z))) (set! z 2) (list z (f))))

(section "4.1.7 Inclusion")
(include "data/included.scm")
(test 42 included-value)
(test 10 (included-double 5))
(include-ci "data/included-ci.scm")
(test 'folded included-ci-value)
(test 7 (let () (include "data/included.scm") (- included-value 35)))

(test-report)
