;; R7RS-small 4.2: derived expression types.
(import (scheme base) (scheme write) (scheme lazy) (scheme case-lambda)
        (scheme inexact) (conformance test))

(define (output-of thunk)
  (let ((port (open-output-string)))
    (parameterize ((current-output-port port)) (thunk))
    (get-output-string port)))

(section "4.2.1 Conditionals: cond")
(test 'greater (cond ((> 3 2) 'greater) ((< 3 2) 'less)))
(test 'equal (cond ((> 3 3) 'greater) ((< 3 3) 'less) (else 'equal)))
(test 2 (cond ((assv 'b '((a 1) (b 2))) => cadr) (else #f)))
(test 7 (cond ((+ 3 4)) (else 'no)))
(test 'b (cond (#f 1) (else 'a 'b)))
(test-values (1 2) (cond (#t (values 1 2))))
(test-values (1 2) (cond ((list 1 2) => (lambda (l) (apply values l)))))

(section "4.2.1 Conditionals: case")
(test 'composite (case (* 2 3) ((2 3 5 7) 'prime) ((1 4 6 8 9) 'composite)))
(test 'c (case (car '(c d)) ((a e i o u) 'vowel) ((w y) 'semivowel) (else => (lambda (x) x))))
(test 'vowel (case (car '(e d)) ((a e i o u) 'vowel) ((w y) 'semivowel) (else 'other)))
(test 'other (case 'z ((a) 1) (else 'other)))
(test 4 (case 3 ((3) => (lambda (x) (+ x 1))) (else 0)))
;; keys are compared with eqv?
(test 'char (case #\a ((#\a) 'char) (else 'no)))
(test 'num (case 2.5 ((2.5) 'num) (else 'no)))
(test 'empty (case '() ((()) 'empty) (else 'no)))
(test 'no (case "a" (("a") 'string) (else 'no)))
(test 'b (case 1 ((1) 'a 'b) (else 'c)))

(section "4.2.1 Conditionals: and, or")
(test #t (and (= 2 2) (> 2 1)))
(test #f (and (= 2 2) (< 2 1)))
(test '(f g) (and 1 2 'c '(f g)))
(test #t (and))
(test #t (or (= 2 2) (> 2 1)))
(test #t (or (= 2 2) (< 2 1)))
(test #f (or #f #f #f))
(test '(b c) (or (memq 'b '(a b c)) (/ 3 0)))
(test #f (or))
(test #f (and #f (car '())))
(test-values (1 2) (and #t (values 1 2)))
(test-values (1 2) (or #f (values 1 2)))

(section "4.2.1 Conditionals: when, unless")
(test "12" (output-of (lambda () (when (= 1 1.0) (display "1") (display "2")))))
(test "" (output-of (lambda () (unless (= 1 1.0) (display "1") (display "2")))))
(test 'last (when #t 'first 'last))
(test 'last (unless #f 'first 'last))

(section "4.2.1 Conditionals: cond-expand")
(test 'r7rs (cond-expand (r7rs 'r7rs) (else 'other)))
(test 'else (cond-expand (no-such-feature-xyz 'no) (else 'else)))
(test 'base (cond-expand ((library (scheme base)) 'base) (else 'no)))
(test 'no-lib (cond-expand ((library (no such library)) 'yes) (else 'no-lib)))
(test 'and (cond-expand ((and r7rs (not no-such-feature-xyz)) 'and) (else 'no)))
(test 'or (cond-expand ((or no-such-feature-xyz r7rs) 'or) (else 'no)))
(test 'not (cond-expand ((not no-such-feature-xyz) 'not) (else 'no)))
(test 'first (cond-expand (r7rs 'first) (r7rs 'second)))

(section "4.2.2 Binding constructs")
(test 6 (let ((x 2) (y 3)) (* x y)))
(test 35 (let ((x 2) (y 3)) (let ((x 7) (z (+ x y))) (* z x))))
(test 70 (let ((x 2) (y 3)) (let* ((x 7) (z (+ x y))) (* z x))))
(test 2 (let* ((x 1) (x (+ x 1))) x))
(test 'body (let () 'body))
(test #t (letrec ((even? (lambda (n) (if (zero? n) #t (odd? (- n 1)))))
                  (odd? (lambda (n) (if (zero? n) #f (even? (- n 1))))))
           (even? 88)))
(test 5 (letrec* ((p (lambda (x) (+ 1 (q (- x 1)))))
                  (q (lambda (y) (if (zero? y) 0 (+ 1 (p (- y 1))))))
                  (x (p 5))
                  (y x))
          y))
(test 35 (let-values (((root rem) (exact-integer-sqrt 32))) (* root rem)))
(test '(x y x y) (let ((a 'a) (b 'b) (x 'x) (y 'y))
                   (let*-values (((a b) (values x y)) ((x y) (values a b)))
                     (list a b x y))))
(test '(1 (2 3)) (let-values (((a . rest) (values 1 2 3))) (list a rest)))
(test '(1 2 3) (let-values ((all (values 1 2 3))) all))
;; let-values inits see the outer bindings, not each other
(test '(outer 1) (let ((a 'outer)) (let-values (((a) (values 1)) ((b) (values a))) (list b a))))
(test '(1 1) (let ((a 'outer)) (let*-values (((a) (values 1)) ((b) (values a))) (list b a))))

(section "4.2.3 Sequencing")
(define x 0)
(test 6 (and (= x 0) (begin (set! x 5) (+ x 1))))
(test "4 plus 1 equals 5"
      (output-of (lambda () (begin (display "4 plus 1 equals ") (display (+ 4 1))))))
(begin (define seq-a 1) (define seq-b 2))
(test 3 (+ seq-a seq-b))
(test-values (1 2) (begin 0 (values 1 2)))

(section "4.2.4 Iteration")
(test #(0 1 2 3 4) (do ((vec (make-vector 5)) (i 0 (+ i 1))) ((= i 5) vec) (vector-set! vec i i)))
(test 25 (let ((x '(1 3 5 7 9))) (do ((x x (cdr x)) (sum 0 (+ sum (car x)))) ((null? x) sum))))
(test '((6 1 3) (-5 -2))
      (let loop ((numbers '(3 -2 1 6 -5)) (nonneg '()) (neg '()))
        (cond ((null? numbers) (list nonneg neg))
              ((>= (car numbers) 0) (loop (cdr numbers) (cons (car numbers) nonneg) neg))
              ((< (car numbers) 0) (loop (cdr numbers) nonneg (cons (car numbers) neg))))))
;; do with no step keeps the variable; each iteration gets fresh bindings
(test 3 (do ((i 0 (+ i 1)) (k 3)) ((= i 2) k)))
(test '(2 1 0) (let ((procs '()))
                 (do ((i 0 (+ i 1))) ((= i 3))
                   (set! procs (cons (lambda () i) procs)))
                 (map (lambda (p) (p)) procs)))
(test 'loop (let loop () 'loop))

(section "4.2.5 Delayed evaluation")
(test 3 (force (delay (+ 1 2))))
(test '(3 3) (let ((p (delay (+ 1 2)))) (list (force p) (force p))))
(define integers
  (letrec ((next (lambda (n) (delay (cons n (next (+ n 1)))))))
    (next 0)))
(define head (lambda (stream) (car (force stream))))
(define tail (lambda (stream) (cdr (force stream))))
(test 2 (head (tail (tail integers))))
(define (stream-filter p? s)
  (delay-force
   (if (null? (force s))
       (delay '())
       (let ((h (car (force s)))
             (t (cdr (force s))))
         (if (p? h)
             (delay (cons h (stream-filter p? t)))
             (stream-filter p? t))))))
(test 5 (head (tail (tail (stream-filter odd? integers)))))
(define count 0)
(define p (delay (begin (set! count (+ count 1))
                        (if (> count x) count (force p)))))
(set! x 5)
(test #t (promise? p))
(test 6 (force p))
(test #t (promise? p))
(test 6 (begin (set! x 10) (force p)))
;; delay-force chains run in constant space
(define (loop-promise n) (delay-force (if (= n 0) (delay 'end) (loop-promise (- n 1)))))
(test 'end (force (loop-promise 10000)))
(test #t (promise? (make-promise 1)))
(test 1 (force (make-promise 1)))
(test #t (let ((p (delay 1))) (eq? p (make-promise p))))
(test #f (promise? 5))
(test #t (promise? (car (list (delay (* 3 7))))))
;; forcing runs once, even when the promise is forced again from inside
(test 1 (let* ((n 0) (p (delay (begin (set! n (+ n 1)) n)))) (force p) (force p)))

(section "4.2.6 Dynamic bindings")
(define radix
  (make-parameter 10 (lambda (x)
                       (if (and (exact-integer? x) (<= 2 x 16))
                           x
                           (error "invalid radix")))))
(define (f n) (number->string n (radix)))
(test "12" (f 12))
(test "1100" (parameterize ((radix 2)) (f 12)))
(test "12" (f 12))
(test-error (parameterize ((radix 0)) (f 12)))
(test 10 (radix))
;; the converter is applied to the initial value and to parameterize values
(define p2 (make-parameter 1 (lambda (x) (* x 10))))
(test 10 (p2))
(test 20 (parameterize ((p2 2)) (p2)))
(test 10 (p2))
(test '(2 1) (let ((q (make-parameter 1)))
               (list (parameterize ((q 2)) (q)) (q))))
(test 'outer (let ((q (make-parameter 'outer)))
               (let ((k (call-with-current-continuation
                         (lambda (c) (parameterize ((q 'inner)) (c 'escaped))))))
                 (q))))

(section "4.2.7 Exception handling")
(test 42 (guard (condition ((assq 'a condition) => cdr) ((assq 'b condition)))
           (raise (list (cons 'a 42)))))
(test '(b . 23) (guard (condition ((assq 'a condition) => cdr) ((assq 'b condition)))
                  (raise (list (cons 'b 23)))))
(test 'else (guard (e (#f 'no) (else 'else)) (raise 1)))
(test 'body (guard (e (#t 'handler)) 'body))
(test-values (1 2) (guard (e (#t 'handler)) (values 1 2)))
(test "caught" (guard (e ((string? e) e)) (raise "caught")))
(test "msg" (guard (e ((error-object? e) (error-object-message e))) (error "msg" 1 2)))
;; no clause matches: re-raised (continuably) to the outer handler
(test 'outer (guard (e ((eq? e 'x) 'outer))
               (guard (e ((eq? e 'y) 'inner))
                 (raise 'x))))
(test 11 (with-exception-handler
          (lambda (e) 10)
          (lambda ()
            (guard (e ((eq? e 'other) 'no))
              (+ 1 (raise-continuable 'c))))))
;; the guard clauses run in the guard's dynamic environment
(test 'out (let ((q (make-parameter 'out)))
             (guard (e (#t (q))) (parameterize ((q 'in)) (raise 'x)))))

(section "4.2.8 Quasiquotation")
(test '(list 3 4) `(list ,(+ 1 2) 4))
(test '(list a (quote a)) (let ((name 'a)) `(list ,name ',name)))
(test '(a 3 4 5 6 b) `(a ,(+ 1 2) ,@(map abs '(4 -5 6)) b))
(test '((foo 7) . cons) `(( foo ,(- 10 3)) ,@(cdr '(c)) . ,(car '(cons))))
(test #(10 5 2 4 3 8) `#(10 5 ,(sqrt 4) ,@(map sqrt '(16 9)) 8))
(test '(list foo bar baz) (let ((foo '(foo bar)) (@baz 'baz)) `(list ,@foo , @baz)))
(test '(a `(b ,(+ 1 2) ,(foo 4 d) e) f) `(a `(b ,(+ 1 2) ,(foo ,(+ 1 3) d) e) f))
(test '(a `(b ,x ,'y d) e) (let ((name1 'x) (name2 'y)) `(a `(b ,,name1 ,',name2 d) e)))
(test '(list 3 4) (quasiquote (list (unquote (+ 1 2)) 4)))
(test '(quasiquote (list (unquote (+ 1 2)) 4)) '(quasiquote (list (unquote (+ 1 2)) 4)))
(test '((1 2) 3 4 five 6) (let ((a 3)) `((1 2) ,a ,4 ,'five 6)))
(test '(1 . 2) `(1 . ,(+ 1 1)))
(test '(1 2 3) `(1 ,@'(2 3)))
(test '(1 2 3) `(1 ,@'() 2 3))
(test 5 `,(+ 2 3))
;; constructed structure is fresh and mutable
(test '(9 2) (let ((l `(,(+ 0 1) 2))) (set-car! l 9) l))

(section "4.2.9 Case-lambda")
(define range
  (case-lambda
    ((e) (range 0 e))
    ((b e) (do ((r '() (cons e r)) (e (- e 1) (- e 1))) ((< e b) r)))))
(test '(0 1 2) (range 3))
(test '(3 4) (range 3 5))
(define plus
  (case-lambda
    (() 0)
    ((x) x)
    ((x y) (+ x y))
    ((x y . rest) (apply plus (+ x y) rest))))
(test '(0 1 3 6 10) (list (plus) (plus 1) (plus 1 2) (plus 1 2 3) (plus 1 2 3 4)))
(test 'rest ((case-lambda ((a b) 'two) (args 'rest)) 1))
(test 'first ((case-lambda ((a) 'first) ((b) 'second)) 1))

(test-report)
