;; R7RS-small chapter 5: program structure.
;; 5.7 (the REPL) is not covered here: a program cannot drive a REPL
;; portably. tulip's REPL is tested in tests/test_system.py.
(import (scheme base)
        (scheme write)
        (conformance test)
        ;; 5.2 import sets
        (only (scheme base) car)
        (prefix (only (scheme base) cdr cons) base:)
        (rename (only (scheme base) list) (list make-a-list))
        (except (only (scheme base) vector vector-ref vector?) vector?)
        (prefix (rename (only (scheme base) length) (length len)) my-)
        ;; 5.6.2, the report's library example
        (only (example life) life)
        (rename (prefix (example grid) grid-)
                (grid-make make-grid))
        ;; 5.6.1: one loading however many imports
        (only (conformance counter) a)
        (only (conformance counter) b loads)
        (conformance decls))

(section "5.1 Programs")
(begin (define begun-1 1) (define begun-2 (+ begun-1 1)))
(test 2 begun-2)
(test 'expression-ran (begin 'expression-ran))

(section "5.2 Import declarations")
(test '(1 . 2) (base:cons 1 (base:cdr '(0 . 2))))
(test '(1 2) (make-a-list 1 2))
(test 2 (my-len '(a b)))
(test 1 (vector-ref (vector 1) 0))
(test 'a a)
(test 'b b)

(section "5.3 Variable definitions")
(define add3 (lambda (x) (+ x 3)))
(test 6 (add3 3))
(define first car)
(test 1 (first '(1 2)))
(define (curried a) (lambda (b) (+ a b)))
(test 5 ((curried 2) 3))
(define (all-args . args) args)
(test '(1 2) (all-args 1 2))
(define (some-args a . rest) (list a rest))
(test '(1 (2 3)) (some-args 1 2 3))
;; at top level, define on a defined variable acts as set!
(define redefined 1)
(define (get-redefined) redefined)
(define redefined 2)
(test 2 (get-redefined))
(test 45 (let ((x 5))
           (define foo (lambda (y) (bar x y)))
           (define bar (lambda (a b) (+ (* a b) a)))
           (foo (+ x 3))))
(test 45 (let ((x 5))
           (letrec* ((foo (lambda (y) (bar x y)))
                     (bar (lambda (a b) (+ (* a b) a))))
             (foo (+ x 3)))))
(test 3 (let () (begin (define p 1) (define q 2)) (+ p q)))
(define-values (x y) (exact-integer-sqrt 17))
(test '(4 1) (list x y))
(test 3 (let () (define-values (x y) (values 1 2)) (+ x y)))
(define-values (dv-a . dv-rest) (values 1 2 3))
(test '(1 (2 3)) (list dv-a dv-rest))
(define-values dv-all (values 4 5))
(test '(4 5) dv-all)
(define-values () (values))
(test '(6 (7)) (let () (define-values (p . q) (values 6 7)) (list p q)))

(section "5.4 Syntax definitions")
(test '(2 1) (let ((x 1) (y 2))
               (define-syntax swap!
                 (syntax-rules ()
                   ((swap! a b)
                    (let ((tmp a))
                      (set! a b)
                      (set! b tmp)))))
               (swap! x y)
               (list x y)))
(define-syntax top-level-macro (syntax-rules () ((_ v) (list 'got v))))
(test '(got 1) (top-level-macro 1))
;; a macro can expand into definitions
(define-syntax define-two
  (syntax-rules () ((_ a b v) (begin (define a v) (define b v)))))
(define-two two-a two-b 'both)
(test '(both both) (list two-a two-b))
(test 'inner (let () (define-two i j 'inner) i))

(section "5.5 Record-type definitions")
(define-record-type <pare>
  (kons x y)
  pare?
  (x kar set-kar!)
  (y kdr))
(test #t (pare? (kons 1 2)))
(test #f (pare? (cons 1 2)))
(test 1 (kar (kons 1 2)))
(test 2 (kdr (kons 1 2)))
(test 3 (let ((k (kons 1 2))) (set-kar! k 3) (kar k)))
;; fields not in the constructor; constructor fields in any order
(define-record-type thing (make-thing b a) thing? (a thing-a) (b thing-b) (c thing-c set-thing-c!))
(test '(1 2 3) (let ((t (make-thing 2 1))) (set-thing-c! t 3) (list (thing-a t) (thing-b t) (thing-c t))))
;; generative: a second type with the same shape is distinct
(define-record-type <pare2> (kons2 x y) pare2? (x kar2) (y kdr2))
(test #f (pare? (kons2 1 2)))
(test #f (pare2? (kons 1 2)))
(test '(#f #f #f #f #f) (map pare? (list 1 'a "s" (vector 1 2) (lambda () 1))))
(test #f (vector? (kons 1 2)))
(test #f (procedure? (kons 1 2)))
;; records are mutable and distinct objects
(test #f (eq? (kons 1 2) (kons 1 2)))
(define-record-type empty-record (make-empty-record) empty-record?)
(test #t (empty-record? (make-empty-record)))

(section "5.6 Libraries")
(test 1 loads)
(test 'renamed external-name)
(test '(1 2) (list first-begin second-begin))
(test 3 included-value)
(test 'ci included-ci-value)
(test 'r7rs expanded)
(test 'yes from-cond-expand)

(section "5.6.2 Library example")
(define grid (make-grid 24 24))
(grid-set! grid 1 1 #true)
(grid-set! grid 2 2 #true)
(grid-set! grid 3 0 #true)
(grid-set! grid 3 1 #true)
(grid-set! grid 3 2 #true)
(define (live-cells g)
  (let ((cells '()))
    (grid-each g (lambda (i j v) (if v (set! cells (cons (list i j) cells)))))
    (reverse cells)))
(define (run-life n)
  (let ((port (open-output-string)))
    (parameterize ((current-output-port port)) (life grid n))
    (get-output-string port)))
(define printed (run-life 4))
;; after four generations a glider has moved one cell down and to the right
(test '((2 2) (3 3) (4 1) (4 2) (4 3)) (live-cells grid))
;; each generation prints a clear-screen sequence and 24 lines of 24 cells
(test (* 4 (+ 7 (* 24 25))) (string-length printed))

(test-report)
