;; R7RS-small 6.1: equivalence predicates.
;; Cases the report marks "unspecified" are not tested.
(import (scheme base) (conformance test))

(section "6.1 eqv?")
(test #t (eqv? 'a 'a))
(test #f (eqv? 'a 'b))
(test #t (eqv? 2 2))
(test #f (eqv? 2 2.0))
(test #t (eqv? '() '()))
(test #t (eqv? 100000000 100000000))
(test #t (eqv? (expt 10 40) (expt 10 40)))
(test #t (eqv? 1/2 (/ 2 4)))
(test #f (eqv? 0.0 +nan.0))
(test #f (eqv? (cons 1 2) (cons 1 2)))
(test #f (eqv? (lambda () 1) (lambda () 2)))
(test #t (let ((p (lambda (x) x))) (eqv? p p)))
(test #f (eqv? #f 'nil))
(test #t (eqv? #t #t))
(test #t (eqv? #f #f))
(test #f (eqv? #t #f))
(test #t (eqv? #\a #\a))
(test #f (eqv? #\a #\b))
(test #t (eqv? 1.5 1.5))
(test #f (eqv? 1 1.0))
(test #f (eqv? "" 'a))
(test #f (eqv? '() #f))
(test #f (eqv? (vector) (vector 1)))
(test #f (eqv? (string #\a) (string #\a)))
(define gen-counter
  (lambda ()
    (let ((n 0))
      (lambda () (set! n (+ n 1)) n))))
(test #t (let ((g (gen-counter))) (eqv? g g)))
(test #f (eqv? (gen-counter) (gen-counter)))
(test #f (letrec ((f (lambda () (if (eqv? f g) 'f 'both)))
                  (g (lambda () (if (eqv? f g) 'g 'both))))
           (eqv? f g)))
(test #t (let ((x '(a))) (eqv? x x)))
(test #t (let ((v (vector 1))) (eqv? v v)))
(test #t (let ((s (string #\a))) (eqv? s s)))
(test #t (let ((b (bytevector 1))) (eqv? b b)))
(test #f (eqv? (bytevector 1) (bytevector 1)))
(test #f (eqv? 0.0 -0.0))

(section "6.1 eq?")
(test #t (eq? 'a 'a))
(test #f (eq? (list 'a) (list 'a)))
(test #t (eq? '() '()))
(test #t (eq? car car))
(test #t (let ((x '(a))) (eq? x x)))
(test #t (let ((x '#())) (eq? x x)))
(test #t (let ((p (lambda (x) x))) (eq? p p)))
(test #t (eq? #t #t))
(test #f (eq? #t #f))
(test #f (eq? (vector 1) (vector 1)))
(test #f (eq? (string #\a) (string #\a)))

(section "6.1 equal?")
(test #t (equal? 'a 'a))
(test #t (equal? '(a) '(a)))
(test #t (equal? '(a (b) c) '(a (b) c)))
(test #t (equal? "abc" "abc"))
(test #f (equal? "abc" "abC"))
(test #t (equal? 2 2))
(test #f (equal? 2 2.0))
(test #t (equal? (make-vector 5 'a) (make-vector 5 'a)))
(test #t (equal? (bytevector 1 2) (bytevector 1 2)))
(test #f (equal? (bytevector 1 2) (bytevector 1 3)))
(test #t (equal? '#1=(a b . #1#) '#2=(a b a b . #2#)))
(test #t (equal? #(1 (2 #(3))) (vector 1 (list 2 (vector 3)))))
(test #f (equal? '(1 2) '(1 2 3)))
(test #f (equal? '(1 . 2) '(1 2)))
(test #t (equal? '() '()))
(test #f (equal? '() #f))
(test #t (equal? #\a #\a))
(test #t (equal? car car))
;; circular structures terminate
(test #t (let ((a (list 1 2)) (b (list 1 2)))
           (set-cdr! (cdr a) a)
           (set-cdr! (cdr b) b)
           (equal? a b)))
(test #t (let ((v (vector 1 #f)) (w (vector 1 #f)))
           (vector-set! v 1 v)
           (vector-set! w 1 w)
           (equal? v w)))

(test-report)
