;; R7RS-small 6.10: control features, 6.11: exceptions, 6.12: environments
;; and evaluation.
(import (scheme base) (scheme char) (scheme inexact) (scheme write) (scheme read)
        (scheme eval) (scheme repl) (scheme r5rs) (conformance test))

(define (output-of thunk)
  (let ((port (open-output-string)))
    (parameterize ((current-output-port port)) (thunk))
    (get-output-string port)))

(section "6.10 procedure?, apply")
(test #t (procedure? car))
(test #f (procedure? 'car))
(test #t (procedure? (lambda (x) (* x x))))
(test #f (procedure? '(lambda (x) (* x x))))
(test #t (call-with-current-continuation procedure?))
(test 7 (apply + (list 3 4)))
(define compose (lambda (f g) (lambda args (f (apply g args)))))
(test 30 ((compose sqrt *) 12 75))
(test '(1 2 3 4) (apply list 1 2 '(3 4)))
(test '() (apply list '()))
(test-values (1 2) (apply values '(1 2)))

(section "6.10 map, for-each and friends")
(test '(b e h) (map cadr '((a b) (d e) (g h))))
(test '(1 4 27 256 3125) (map (lambda (n) (expt n n)) '(1 2 3 4 5)))
(test '(5 7 9) (map + '(1 2 3) '(4 5 6 7)))
(test #t (let ((r (let ((count 0))
                    (map (lambda (ignored) (set! count (+ count 1)) count) '(a b)))))
           (or (equal? r '(1 2)) (equal? r '(2 1)))))
(test '(2 3 4) (let ((ones (list 1))) (set-cdr! ones ones) (map + '(1 2 3) ones)))
(test '() (map car '()))
(test "abdegh" (string-map char-foldcase "AbdEgH"))
(test "IBM" (string-map (lambda (c) (integer->char (+ 1 (char->integer c)))) "HAL"))
(test "StUdLyCaPs" (string-map (lambda (c k) ((if (eqv? k #\u) char-upcase char-downcase) c))
                               "studlycaps xxx" "ululululul"))
(test #(b e h) (vector-map cadr '#((a b) (d e) (g h))))
(test #(1 4 27 256 3125) (vector-map (lambda (n) (expt n n)) '#(1 2 3 4 5)))
(test #(5 7 9) (vector-map + '#(1 2 3) '#(4 5 6 7)))
(test #(0 1 4 9 16) (let ((v (make-vector 5)))
                      (for-each (lambda (i) (vector-set! v i (* i i))) '(0 1 2 3 4))
                      v))
(test '(3 2 1) (let ((acc '())) (for-each (lambda (x) (set! acc (cons x acc))) '(1 2 3)) acc))
(test '((1 . a) (2 . b)) (let ((acc '()))
                          (for-each (lambda (x y) (set! acc (cons (cons x y) acc))) '(1 2 3) '(a b))
                          (reverse acc)))
(test '(101 100 99 98 97) (let ((v '()))
                            (string-for-each (lambda (c) (set! v (cons (char->integer c) v))) "abcde")
                            v))
(test '((#\a . #\x) (#\b . #\y)) (let ((v '()))
                                  (string-for-each (lambda (a b) (set! v (cons (cons a b) v))) "abc" "xy")
                                  (reverse v)))
(test '(0 1 4 9 16) (let ((v (make-list 5)))
                      (vector-for-each (lambda (i) (list-set! v i (* i i))) '#(0 1 2 3 4))
                      v))
(test '(4 6) (let ((acc '()))
               (vector-for-each (lambda (a b) (set! acc (cons (+ a b) acc))) #(1 2 3) #(3 4))
               (reverse acc)))

(section "6.10 call/cc")
(test -3 (call-with-current-continuation
          (lambda (exit)
            (for-each (lambda (x) (if (negative? x) (exit x))) '(54 0 37 -3 245 19))
            #t)))
(define list-length
  (lambda (obj)
    (call-with-current-continuation
     (lambda (return)
       (letrec ((r (lambda (obj)
                     (cond ((null? obj) 0)
                           ((pair? obj) (+ (r (cdr obj)) 1))
                           (else (return #f))))))
         (r obj))))))
(test 4 (list-length '(1 2 3 4)))
(test #f (list-length '(a b . c)))
(test 3 (call/cc (lambda (k) (+ 1 (k 3)))))
(test-values (1 2) (call/cc (lambda (k) (k 1 2))))
(test 5 (call-with-values (lambda () (call/cc (lambda (k) (k 2 3)))) +))
;; an escape procedure can be stored and called again later
(test '(0 1 2) (let ((k #f) (acc '()))
                 (let ((n (call/cc (lambda (c) (set! k c) 0))))
                   (set! acc (cons n acc))
                   (if (< n 2) (k (+ n 1)) (reverse acc)))))

(section "6.10 values, call-with-values")
(test 5 (call-with-values (lambda () (values 4 5)) (lambda (a b) b)))
(test -1 (call-with-values * -))
(test '() (call-with-values values list))
(test '(1 2 3) (call-with-values (lambda () (values 1 2 3)) list))
(test 1 (call-with-values (lambda () 1) (lambda (x) x)))
;; non-final positions accept any number of values
(test 'ok (begin (values 1 2) (values) 'ok))

(section "6.10 dynamic-wind")
(test '(connect talk1 disconnect connect talk2 disconnect)
      (let ((path '())
            (c #f))
        (let ((add (lambda (s) (set! path (cons s path)))))
          (dynamic-wind
           (lambda () (add 'connect))
           (lambda ()
             (add (call-with-current-continuation
                   (lambda (c0) (set! c c0) 'talk1))))
           (lambda () (add 'disconnect)))
          (if (< (length path) 4)
              (c 'talk2)
              (reverse path)))))
(test '(before during after) (let ((l '()))
                               (dynamic-wind (lambda () (set! l (cons 'before l)))
                                             (lambda () (set! l (cons 'during l)))
                                             (lambda () (set! l (cons 'after l))))
                               (reverse l)))
(test-values (1 2) (dynamic-wind (lambda () #f) (lambda () (values 1 2)) (lambda () #f)))
;; nested: inner after runs first on exit, outer before first on entry
(test '(out-before in-before in-after out-after out-before in-before in-after out-after)
      (let ((l '()) (k #f) (n 0))
        (define (note x) (set! l (cons x l)))
        (dynamic-wind
         (lambda () (note 'out-before))
         (lambda ()
           (dynamic-wind
            (lambda () (note 'in-before))
            (lambda () (call/cc (lambda (c) (set! k c))))
            (lambda () (note 'in-after))))
         (lambda () (note 'out-after)))
        (set! n (+ n 1))
        (if (< n 2) (k 'again) (reverse l))))
;; escaping runs after; errors through guard run after too
(test '(after caught) (let ((l '()))
                        (let ((r (guard (e (#t 'caught))
                                   (dynamic-wind (lambda () #f)
                                                 (lambda () (raise 'x))
                                                 (lambda () (set! l (cons 'after l)))))))
                          (reverse (cons r l)))))

(section "6.11 Exceptions")
(test "condition: an-error\n"
      (output-of (lambda ()
                   (call-with-current-continuation
                    (lambda (k)
                      (with-exception-handler
                       (lambda (x) (display "condition: ") (write x) (newline) (k 'exception))
                       (lambda () (+ 1 (raise 'an-error)))))))))
(test 'exception (call-with-current-continuation
                  (lambda (k)
                    (with-exception-handler
                     (lambda (x) (k 'exception))
                     (lambda () (+ 1 (raise 'an-error)))))))
;; a handler returning from raise raises a secondary exception in the
;; handler's dynamic environment (here, the guard's)
(test 'secondary (guard (e (#t 'secondary))
                   (with-exception-handler
                    (lambda (x) 'returned)
                    (lambda () (+ 1 (raise 'an-error))))))
(test "something went wrong\n"
      (let ((port (open-output-string)))
        (guard (e (#t #f))
          (parameterize ((current-output-port port))
            (with-exception-handler
             (lambda (x) (display "something went wrong\n"))
             (lambda () (+ 1 (raise 'an-error))))))
        (get-output-string port)))
(test 65 (with-exception-handler
          (lambda (con) (cond ((string? con) 'shown) (else 'warning)) 42)
          (lambda () (+ (raise-continuable "should be a number") 23))))
(test "should be a number"
      (output-of (lambda ()
                   (with-exception-handler
                    (lambda (con)
                      (cond ((string? con) (display con))
                            (else (display "a warning has been issued")))
                      42)
                    (lambda () (+ (raise-continuable "should be a number") 23))))))
;; the handler runs with the outer handler installed
(test 'outer (with-exception-handler
              (lambda (e) 'outer)
              (lambda ()
                (with-exception-handler
                 (lambda (e) (raise-continuable 'again))
                 (lambda () (raise-continuable 'first))))))
(define (null-list? l)
  (cond ((pair? l) #f)
        ((null? l) #t)
        (else (error "null-list?: argument out of domain" l))))
(test #t (null-list? '()))
(test '(#t "null-list?: argument out of domain" (1))
      (guard (e ((error-object? e) (list #t (error-object-message e) (error-object-irritants e))))
        (null-list? 1)))
(test '() (guard (e (#t (error-object-irritants e))) (error "no irritants")))
(test #f (error-object? 'sym))
(test #f (guard (e (#t (error-object? e))) (raise 42)))
(test #t (guard (e (#t (read-error? e))) (read (open-input-string "(1 2"))))
(test #t (guard (e (#t (read-error? e))) (read (open-input-string ")"))))
(test #t (guard (e (#t (file-error? e))) (open-input-file "no/such/file/conformance-xyz")))
(test #f (read-error? 'x))
(test #f (file-error? 'x))

(section "6.12 Environments and evaluation")
(test 21 (eval '(* 7 3) (environment '(scheme base))))
(test 20 (let ((f (eval '(lambda (f x) (f x x)) (null-environment 5)))) (f + 10)))
(test 6 (eval '(+ 1 2 3) (scheme-report-environment 5)))
(test-error (eval '(define foo 32) (environment '(scheme base))))
(test 3 (eval '(let ((x 1)) (+ x 2)) (environment '(scheme base))))
(test 'ok (eval '(cond-expand (r7rs 'ok) (else 'no)) (environment '(scheme base))))
(test 4 (eval '(square 2) (environment '(only (scheme base) square))))
(test 2 (eval '(my-car '(2 3)) (environment '(rename (scheme base) (car my-car)))))
(test 1 (eval '(begin (define conformance-eval-var 1) conformance-eval-var) (interaction-environment)))
(test 2 (eval '(begin (define-syntax two (syntax-rules () ((_) 2))) (two)) (interaction-environment)))
(test-values (1 2) (eval '(values 1 2) (environment '(scheme base))))

(test-report)
