;; R7RS-small 6.13: input and output, and 6.14: system interface.
;; exit and emergency-exit end the process, so they are tested through the
;; CLI in tests/test_system.py instead.
(import (scheme base) (scheme char) (scheme read) (scheme write) (scheme file)
        (scheme load) (scheme eval) (scheme repl) (scheme process-context)
        (scheme time) (conformance test))

(define (written x)
  (let ((p (open-output-string))) (write x p) (get-output-string p)))
(define (displayed x)
  (let ((p (open-output-string))) (display x p) (get-output-string p)))
(define tmp-text "conformance-io-text.tmp")
(define tmp-binary "conformance-io-binary.tmp")
(define tmp-load "conformance-io-load.tmp")
;; an escape from with-output-to-file leaves its port open (6.13.1), which
;; can stop the file being deleted on some systems: it gets its own file,
;; and cleanup tolerates a file it cannot delete yet (run.py's next run will)
(define tmp-escape "conformance-io-escape.tmp")
(define (cleanup)
  (for-each (lambda (f)
              (if (file-exists? f)
                  (guard (e ((file-error? e) #f)) (delete-file f))))
            (list tmp-text tmp-binary tmp-load tmp-escape)))
(cleanup)

(section "6.13.1 Ports: kinds and predicates")
(define sp (open-input-string "abc"))
(define op (open-output-string))
(define bip (open-input-bytevector #u8(1 2 3)))
(define bop (open-output-bytevector))
(test '(#t #f #t #f #t) (list (input-port? sp) (output-port? sp) (textual-port? sp) (binary-port? sp) (port? sp)))
(test '(#f #t #t #f #t) (list (input-port? op) (output-port? op) (textual-port? op) (binary-port? op) (port? op)))
(test '(#t #f #f #t #t) (list (input-port? bip) (output-port? bip) (textual-port? bip) (binary-port? bip) (port? bip)))
(test '(#f #t #f #t #t) (list (input-port? bop) (output-port? bop) (textual-port? bop) (binary-port? bop) (port? bop)))
(test #f (port? "abc"))
(test #t (input-port? (current-input-port)))
(test #t (output-port? (current-output-port)))
(test #t (output-port? (current-error-port)))
(test #t (textual-port? (current-output-port)))
(test #t (input-port-open? sp))
(close-port sp)
(test #f (input-port-open? sp))
(close-input-port sp)
(test #t (output-port-open? op))
(close-output-port op)
(test #f (output-port-open? op))
(close-port op)

(section "6.13.1 call-with-port, string and bytevector ports")
(define kept #f)
(test 'result (call-with-port (open-input-string "x") (lambda (p) (set! kept p) 'result)))
(test #f (input-port-open? kept))
(test-values (1 2) (call-with-port (open-input-string "x") (lambda (p) (values 1 2))))
(test "piece by piece by piece.\n"
      (parameterize ((current-output-port (open-output-string)))
        (display "piece")
        (display " by piece ")
        (display "by piece.")
        (newline)
        (get-output-string (current-output-port))))
(test "ab" (let ((p (open-output-string)))
             (write-char #\a p) (write-string "b" p)
             (get-output-string p)))
(test "" (get-output-string (open-output-string)))
(test #u8(1 2 3) (let ((p (open-output-bytevector)))
                   (write-u8 1 p) (write-bytevector #u8(2 3) p)
                   (get-output-bytevector p)))
(test #u8() (get-output-bytevector (open-output-bytevector)))

(section "6.13.1 File ports")
(call-with-output-file tmp-text (lambda (p) (write '(a "b" #\c 1.5) p) (newline p) (display "line two" p)))
(test #t (file-exists? tmp-text))
(test '(a "b" #\c 1.5) (call-with-input-file tmp-text read))
(test '("(a \"b\" #\\c 1.5)" "line two")
      (call-with-input-file tmp-text (lambda (p) (let* ((a (read-line p)) (b (read-line p))) (list a b)))))
(with-output-to-file tmp-text (lambda () (display "via with-output-to-file")))
(test "via with-output-to-file" (with-input-from-file tmp-text read-line))
(test-values (1 2) (with-input-from-file tmp-text (lambda () (values 1 2))))
(test #t (let ((p (open-input-file tmp-text))) (let ((r (textual-port? p))) (close-port p) r)))
(let ((p (open-binary-output-file tmp-binary)))
  (write-bytevector #u8(0 1 2 255) p)
  (close-port p))
(test #u8(0 1 2 255) (let* ((p (open-binary-input-file tmp-binary))
                            (b (read-bytevector 10 p)))
                       (close-port p)
                       b))
(test #t (let ((p (open-binary-input-file tmp-binary))) (let ((r (binary-port? p))) (close-port p) r)))
(test #t (guard (e (#t (file-error? e))) (open-input-file "no-such-dir/no-such-file.tmp")))
(test #t (guard (e (#t (file-error? e))) (open-binary-input-file "no-such-dir/no-such-file.tmp")))
(test #t (guard (e (#t (file-error? e))) (open-output-file "no-such-dir/no-such-file.tmp")))
;; the current ports are restored after with-output-to-file escapes
(test #t (let ((before (current-output-port)))
           (call/cc (lambda (k) (with-output-to-file tmp-escape (lambda () (k #f)))))
           (eq? before (current-output-port))))

(section "6.13.2 Input: read")
(define rp (open-input-string "(a . b) #(1 2) \"str\" sym 42 #\\x"))
(test '(a . b) (read rp))
(test #(1 2) (read rp))
(test "str" (read rp))
(test 'sym (read rp))
(test 42 (read rp))
(test #\x (read rp))
(test #t (eof-object? (read rp)))
(test #t (eof-object? (read rp)))
(test #t (eof-object? (read (open-input-string "   ; only a comment\n"))))
(test #t (guard (e (#t (read-error? e))) (read (open-input-string "(1 2"))))
(test #t (guard (e (#t (read-error? e))) (read (open-input-string "\"unterminated"))))
(test '(1 rest) (let ((p (open-input-string "1 rest"))) (list (read p) (read p))))
;; read stops right after the datum
(test #\space (let ((p (open-input-string "abc def"))) (read p) (read-char p)))
(test 'stdin (parameterize ((current-input-port (open-input-string "stdin"))) (read)))

(section "6.13.2 Input: characters, lines, strings")
(define cp (open-input-string "ab\ncd\r\nef\rgh"))
(test #\a (peek-char cp))
(test #\a (read-char cp))
(test #\b (read-char cp))
(test #\newline (peek-char cp))
(test "" (read-line cp))
(test "cd" (read-line cp))
(test "ef" (read-line cp))
(test "gh" (read-line cp))
(test #t (eof-object? (read-line cp)))
(test #t (eof-object? (read-char cp)))
(test #t (eof-object? (peek-char cp)))
(test "abc" (read-line (open-input-string "abc")))
(test "ab" (read-string 2 (open-input-string "abcd")))
(test "abcd" (read-string 10 (open-input-string "abcd")))
(test #t (eof-object? (read-string 2 (open-input-string ""))))
(test "" (read-string 0 (open-input-string "abc")))
(test #t (char-ready? (open-input-string "a")))
(test #t (char-ready? (open-input-string "")))
(test #\z (parameterize ((current-input-port (open-input-string "z"))) (read-char)))
(test "line" (parameterize ((current-input-port (open-input-string "line\nmore"))) (read-line)))
(test #t (eof-object? (eof-object)))
(test #f (eof-object? 'eof))
(test #f (eof-object? ""))

(section "6.13.2 Input: bytes")
(define bp (open-input-bytevector #u8(1 2 3 4 5)))
(test 1 (peek-u8 bp))
(test 1 (read-u8 bp))
(test #t (u8-ready? bp))
(test #u8(2 3) (read-bytevector 2 bp))
(test 4 (read-u8 bp))
(test #u8(5) (read-bytevector 10 bp))
(test #t (eof-object? (read-u8 bp)))
(test #t (eof-object? (peek-u8 bp)))
(test #t (eof-object? (read-bytevector 1 bp)))
(test #t (u8-ready? bp))
(test '(3 #u8(7 8 9 0 0))
      (let ((bv (make-bytevector 5 0)))
        (list (read-bytevector! bv (open-input-bytevector #u8(7 8 9))) bv)))
(test '(2 #u8(0 7 8 0 0))
      (let ((bv (make-bytevector 5 0)))
        (list (read-bytevector! bv (open-input-bytevector #u8(7 8 9)) 1 3) bv)))
(test '(1 #u8(0 0 0 0 7))
      (let ((bv (make-bytevector 5 0)))
        (list (read-bytevector! bv (open-input-bytevector #u8(7 8 9)) 4) bv)))
(test #t (eof-object? (read-bytevector! (make-bytevector 2) (open-input-bytevector #u8()))))

(section "6.13.3 Output: write, write-shared, write-simple, display")
(test "(1 \"two\" #\\3 4.5 sym)" (written '(1 "two" #\3 4.5 sym)))
(test "\"a\\\\b\\\"c\"" (written "a\\b\"c"))
(test "#\\a" (written #\a))
(test "#\\space" (written #\space))
(test "#\\newline" (written #\newline))
(test "|a b|" (written (string->symbol "a b")))
(test "||" (written (string->symbol "")))
(test #t (let ((s (written (string->symbol (string (integer->char #x3BB))))))
           (and (char=? #\| (string-ref s 0)) (char=? #\| (string-ref s (- (string-length s) 1))))))
(test "#(1 #(2))" (written #(1 #(2))))
(test "#u8(1 2)" (written #u8(1 2)))
(test "(a . b)" (written '(a . b)))
(test "(quote a)" (let ((s (written ''a))) (if (string=? s "'a") "(quote a)" s)))
(test "#t" (written #t))
(test "#f" (written #f))
(test "()" (written '()))
;; datum labels only for cycles in write; for all sharing in write-shared
(test "((1) (1))" (let ((x (list 1))) (written (list x x))))
(test "#0=(a b c . #0#)" (let ((x (list 'a 'b 'c))) (set-cdr! (cddr x) x) (written x)))
(test "#0=#(1 #0#)" (let ((v (vector 1 #f))) (vector-set! v 1 v) (written v)))
(test "(#0=(1) #0#)" (let ((x (list 1)) (p (open-output-string)))
                       (write-shared (list x x) p) (get-output-string p)))
(test "((1) (1))" (let ((x (list 1)) (p (open-output-string)))
                    (write-simple (list x x) p) (get-output-string p)))
(test #t (let ((x (list 1 2)) (p (open-output-string)))
           (set-cdr! (cdr x) x)
           (display x p)
           (string? (get-output-string p))))
(test "two" (displayed "two"))
(test "a" (displayed #\a))
(test "a b" (displayed (string->symbol "a b")))
(test "(1 two #\\x)" (let ((s (displayed '(1 "two" #\x)))) (if (string=? s "(1 two x)") "(1 two #\\x)" s)))
(test "(1 two x)" (displayed '(1 "two" #\x)))
(test "\n" (let ((p (open-output-string))) (newline p) (get-output-string p)))
(test "bc" (let ((p (open-output-string))) (write-string "abcd" p 1 3) (get-output-string p)))
(test "bcd" (let ((p (open-output-string))) (write-string "abcd" p 1) (get-output-string p)))
(test #u8(2 3) (let ((p (open-output-bytevector))) (write-bytevector #u8(1 2 3 4) p 1 3) (get-output-bytevector p)))
(test #u8(2 3 4) (let ((p (open-output-bytevector))) (write-bytevector #u8(1 2 3 4) p 1) (get-output-bytevector p)))
(test "x" (let ((p (open-output-string))) (write-char #\x p) (flush-output-port p) (get-output-string p)))
(test 'ok (begin (flush-output-port) 'ok))

(section "6.14 System interface")
(call-with-output-file tmp-load
  (lambda (p) (write '(define conformance-loaded (+ 40 2)) p)))
(load tmp-load)
(test 42 conformance-loaded)
(call-with-output-file tmp-load
  (lambda (p) (write '(define in-env 7) p)))
(define load-env (interaction-environment))
(load tmp-load load-env)
(test 7 (eval 'in-env load-env))
(test #t (file-exists? tmp-load))
(delete-file tmp-load)
(test #f (file-exists? tmp-load))
(test #t (guard (e (#t (file-error? e))) (delete-file tmp-load)))
(test #t (let ((cl (command-line))) (and (pair? cl) (string? (car cl)))))
(test #t (let ((cl (command-line))) (let loop ((l cl)) (or (null? l) (and (string? (car l)) (loop (cdr l)))))))
(test #t (string? (get-environment-variable "PATH")))
(test #f (get-environment-variable "CONFORMANCE_SURELY_UNSET_VARIABLE_XYZ"))
(test #t (let ((vars (get-environment-variables)))
           (and (list? vars)
                (pair? vars)
                (string? (caar vars))
                (string? (cdar vars))
                (assoc "PATH" (map (lambda (p) (cons (string-upcase (car p)) (cdr p))) vars))
                #t)))
(test #t (inexact? (current-second)))
(test #t (> (current-second) 1.3e9))
(test #t (exact-integer? (current-jiffy)))
(test #t (let ((a (current-jiffy)) (b (current-jiffy))) (<= a b)))
(test #t (and (exact-integer? (jiffies-per-second)) (positive? (jiffies-per-second))))

(cleanup)
(test-report)
