;; R7RS-small 6.4: pairs and lists, and 6.5: symbols.
(import (scheme base) (scheme cxr) (scheme char) (scheme read) (scheme write)
        (conformance test))

(define (written x)
  (let ((p (open-output-string))) (write x p) (get-output-string p)))

(section "6.4 Pairs and lists: notation")
(test '(a b c d e) '(a . (b . (c . (d . (e . ()))))))
(test '(a b c . d) '(a . (b . (c . d))))
(define x (list 'a 'b 'c))
(define y x)
(test '(a b c) y)
(test #t (list? y))
(set-cdr! x 4)
(test '(a . 4) x)
(test #t (eqv? x y))
(test '(a . 4) y)
(test #f (list? y))
(set-cdr! x x)
(test #f (list? x))
(test '(quote a) (read (open-input-string "'a")))
(test '(quasiquote a) (read (open-input-string "`a")))
(test '(unquote a) (read (open-input-string ",a")))
(test '(unquote-splicing a) (read (open-input-string ",@a")))

(section "6.4 pair?, cons, car, cdr, set-car!, set-cdr!")
(test #t (pair? '(a . b)))
(test #t (pair? '(a b c)))
(test #f (pair? '()))
(test #f (pair? '#(a b)))
(test '(a) (cons 'a '()))
(test '((a) b c d) (cons '(a) '(b c d)))
(test '("a" b c) (cons "a" '(b c)))
(test '(a . 3) (cons 'a 3))
(test '((a b) . c) (cons '(a b) 'c))
(test #f (let ((p (cons 1 2))) (eq? p (cons 1 2))))
(test 'a (car '(a b c)))
(test '(a) (car '((a) b c d)))
(test 1 (car '(1 . 2)))
(test '(b c d) (cdr '((a) b c d)))
(test 2 (cdr '(1 . 2)))
(test '(3) (let ((f (list 'not-a-constant-list))) (set-car! f 3) f))
(test '(1 . 2) (let ((p (list 1))) (set-cdr! p 2) p))

(section "6.4 c[ad]r compositions")
(define tree '((1 . 2) . (3 . 4)))
(test 1 (caar tree))
(test 3 (cadr tree))
(test 2 (cdar tree))
(test 4 (cddr tree))
(define deep '(((a b) c) (d e) f g))
(test 'a (caaar deep))
(test '(d e) (cadr deep))
(test 'd (caadr deep))
(test 'f (caddr deep))
(test '(g) (cdddr deep))
(test 'g (cadddr deep))
(test '() (cddddr deep))
(test '(b) (cdaar deep))
(test 'c (cadar deep))
(test 'b (cadaar deep))
(test 'e (cadadr deep))
(test '(e) (cdadr deep))
(test '((f g) (e) (c))(list (cddr deep) (cdadr deep) (cdar deep)))

(section "6.4 list procedures")
(test #t (null? '()))
(test #f (null? '(a)))
(test #f (null? #f))
(test #t (list? '(a b c)))
(test #t (list? '()))
(test #f (list? '(a . b)))
(test #f (let ((x (list 'a))) (set-cdr! x x) (list? x)))
(test '(3 3) (make-list 2 3))
(test 2 (length (make-list 2)))
(test '() (make-list 0 'x))
(test '(a 7 c) (list 'a (+ 3 4) 'c))
(test '() (list))
(test 3 (length '(a b c)))
(test 3 (length '(a (b) (c d e))))
(test 0 (length '()))
(test '(x y) (append '(x) '(y)))
(test '(a b c d) (append '(a) '(b c d)))
(test '(a (b) (c)) (append '(a (b)) '((c))))
(test '(a b c . d) (append '(a b) '(c . d)))
(test 'a (append '() 'a))
(test '() (append))
(test '(a) (append '(a)))
(test 5 (append 5))
(test '(1 2 3 4) (append '(1) '() '(2 3) '() '(4)))
(test #t (let ((last (list 3))) (eq? last (cdr (append (list 1) last)))))
(test #f (let ((first (list 1))) (eq? first (append first '(2)))))
(test '(c b a) (reverse '(a b c)))
(test '((e (f)) d (b c) a) (reverse '(a (b c) d (e (f)))))
(test '() (reverse '()))
(test '(c d) (list-tail '(a b c d) 2))
(test '(a b) (list-tail '(a b) 0))
(test 'c (list-ref '(a b c d) 2))
(test 'c (list-ref '(a b c d) (exact (round 1.8))))
(test 'b (let ((c (list 'a 'b))) (set-cdr! (cdr c) c) (list-ref c 3)))
(test '(one two three) (let ((ls (list 'one 'two 'five!))) (list-set! ls 2 'three) ls))

(section "6.4 memq, memv, member")
(test '(a b c) (memq 'a '(a b c)))
(test '(b c) (memq 'b '(a b c)))
(test #f (memq 'a '(b c d)))
(test #f (memq (list 'a) '(b (a) c)))
(test '((a) c) (member (list 'a) '(b (a) c)))
(test '("b" "c") (member "B" '("a" "b" "c") string-ci=?))
(test '(101 102) (memv 101 '(100 101 102)))
(test '(2.0 3) (memv 2.0 '(1 2 2.0 3)))
(test #f (member 5 '()))
(test '(4 5) (member 3 '(1 2 4 5) <))

(section "6.4 assq, assv, assoc")
(define e '((a 1) (b 2) (c 3)))
(test '(a 1) (assq 'a e))
(test '(b 2) (assq 'b e))
(test #f (assq 'd e))
(test #f (assq (list 'a) '(((a)) ((b)) ((c)))))
(test '((a)) (assoc (list 'a) '(((a)) ((b)) ((c)))))
(test '(2 4) (assoc 2.0 '((1 1) (2 4) (3 9)) =))
(test '(5 7) (assv 5 '((2 3) (5 7) (11 13))))
(test #f (assv 1/2 '()))
(test '("B" . 2) (assoc "b" '(("a" . 1) ("B" . 2)) string-ci=?))

(section "6.4 list-copy")
(define a '(1 8 2 8))
(define b (list-copy a))
(set-car! b 3)
(test '(3 8 2 8) b)
(test '(1 8 2 8) a)
(test '(1 2 . 3) (list-copy '(1 2 . 3)))
(test 5 (list-copy 5))
(test '() (list-copy '()))
(test #t (let* ((inner (list 1)) (l (list inner))) (eq? inner (car (list-copy l)))))
(test #f (let ((l (list 1 2))) (eq? l (list-copy l))))

(section "6.5 Symbols")
(test #t (symbol? 'foo))
(test #t (symbol? (car '(a b))))
(test #f (symbol? "bar"))
(test #t (symbol? 'nil))
(test #f (symbol? '()))
(test #f (symbol? #f))
(test #t (symbol=? 'a 'a))
(test #t (symbol=? 'a 'a 'a))
(test #f (symbol=? 'a 'b))
(test #f (symbol=? 'a 'a 'b))
(test "flying-fish" (symbol->string 'flying-fish))
(test "Martin" (symbol->string 'Martin))
(test "Malvina" (symbol->string (string->symbol "Malvina")))
(test "mISSISSIppi" (symbol->string (string->symbol "mISSISSIppi")))
(test #t (eqv? 'bitBlt (string->symbol "bitBlt")))
(test #t (eqv? 'LollyPop (string->symbol (symbol->string 'LollyPop))))
(test #t (string=? "K. Harper, M.D." (symbol->string (string->symbol "K. Harper, M.D."))))
(test #t (eq? (string->symbol "with space") '|with space|))
(test "a|b" (symbol->string (string->symbol "a|b")))
;; read/write invariance, including names that need escaping
(test #t (let loop ((syms (list 'abc (string->symbol "with space") (string->symbol "")
                                (string->symbol "A") (string->symbol "a|b")
                                (string->symbol "1+") (string->symbol "#foo")
                                (string->symbol "."))))
           (or (null? syms)
               (and (eq? (car syms) (read (open-input-string (written (car syms)))))
                    (loop (cdr syms))))))

(test-report)
