;; R7RS-small 6.6: characters, and 6.7: strings.
(import (scheme base) (scheme char) (scheme read) (scheme write) (conformance test))

(define (read-from s) (read (open-input-string s)))
(define (written x)
  (let ((p (open-output-string))) (write x p) (get-output-string p)))
(define (filter-true l)
  (cond ((null? l) '()) ((car l) (cons #t (filter-true (cdr l)))) (else (filter-true (cdr l)))))

(section "6.6 Character names and syntax")
(test #x7 (char->integer #\alarm))
(test #x8 (char->integer #\backspace))
(test #x7F (char->integer #\delete))
(test #x1B (char->integer #\escape))
(test #xA (char->integer #\newline))
(test #x0 (char->integer #\null))
(test #xD (char->integer #\return))
(test #x20 (char->integer #\space))
(test #x9 (char->integer #\tab))
(test 97 (char->integer #\a))
(test 65 (char->integer #\A))
(test 40 (char->integer #\())
(test 32 (char->integer (read-from "#\\ ")))
(test #x3BB (char->integer #\x03BB))
(test #x3BB (char->integer #\x3bb))
(test #\x41 #\A)
(test #f (char=? #\a #\A))
;; #\space followed by a delimiter is the space character
(test '(#\space x) (read-from "(#\\space x)"))
(test '(#\s pace) (list #\s 'pace))
(test #\x (read-from "#\\x"))
(test "#\\a" (written #\a))
(test #\space (read-from (written #\space)))
(test #\newline (read-from (written #\newline)))
(test #\x7 (read-from (written #\alarm)))
(test #\a #\a)

(section "6.6 Character predicates and comparison")
(test #t (char? #\a))
(test #f (char? "a"))
(test #f (char? 97))
(test #t (char=? #\a #\a #\a))
(test #f (char=? #\a #\a #\b))
(test #t (char<? #\a #\b #\c))
(test #f (char<? #\a #\c #\b))
(test #t (char>? #\c #\b #\a))
(test #t (char<=? #\a #\a #\b))
(test #t (char>=? #\b #\b #\a))
(test #f (char>=? #\a #\b))
(test #t (char-ci=? #\A #\a))
(test #t (char-ci=? #\A #\a #\A))
(test #t (char-ci<? #\a #\B #\c))
(test #t (char-ci>? #\C #\b))
(test #t (char-ci<=? #\a #\A #\b))
(test #t (char-ci>=? #\B #\b #\A))
(test #t (char-alphabetic? #\a))
(test #t (char-alphabetic? #\Z))
(test #f (char-alphabetic? #\1))
(test #t (char-alphabetic? #\x3BB))
(test #t (char-numeric? #\7))
(test #f (char-numeric? #\a))
(test #t (char-numeric? #\x0664))
(test #t (char-whitespace? #\space))
(test #t (char-whitespace? #\tab))
(test #t (char-whitespace? #\newline))
(test #t (char-whitespace? #\x00A0))
(test #f (char-whitespace? #\a))
(test #t (char-upper-case? #\A))
(test #f (char-upper-case? #\a))
(test #f (char-upper-case? #\1))
(test #t (char-lower-case? #\a))
(test #f (char-lower-case? #\A))
(test #t (char-lower-case? #\x3BB))
(test 3 (digit-value #\3))
(test 4 (digit-value #\x0664))
(test 0 (digit-value #\x0AE6))
(test #f (digit-value #\x0EA6))
(test #f (digit-value #\a))

(section "6.6 Conversion and case")
(test 955 (char->integer #\x3BB))
(test #\x3BB (integer->char 955))
(test #\a (integer->char (char->integer #\a)))
(test #x10FFFF (char->integer (integer->char #x10FFFF)))
(test #\A (char-upcase #\a))
(test #\A (char-upcase #\A))
(test #\1 (char-upcase #\1))
(test #\a (char-downcase #\A))
(test #\x3BB (char-downcase #\x39B))
(test #\a (char-foldcase #\A))
(test #\x3C3 (char-foldcase #\x3A3))
(test #\x3C3 (char-foldcase #\x3C2))

(section "6.7 String syntax")
(test 39 (string-length "The word \"recursion\" has many meanings."))
(test #\" (string-ref "a\"b" 1))
(test "Another example:\ntwo lines of text"
      (string-append "Another example:" (string #\newline) "two lines of text"))
(test "Here's text containing just one line" "Here's text \
   containing just one line")
(test "a\tb" (string #\a #\tab #\b))
(test #\x3B1 (string-ref "\x03B1; is named GREEK SMALL LETTER ALPHA." 0))
(test '(7 8 9 10 13 34 92 124)
      (map char->integer (string->list "\a\b\t\n\r\"\\\|")))
(test "ab" "a\
          b")
(test "a\nb" "a
b")
(test "\"a\\\\b\"" (written "a\\b"))
(test "a\nb" (read-from (written "a\nb")))
(test "\x41;" "A")

(section "6.7 Basic string procedures")
(test #t (string? "a"))
(test #f (string? #\a))
(test #f (string? 'a))
(test "***" (make-string 3 #\*))
(test 2 (string-length (make-string 2)))
(test "" (make-string 0 #\a))
(test "abc" (string #\a #\b #\c))
(test "" (string))
(test 3 (string-length "abc"))
(test 0 (string-length ""))
(test #\b (string-ref "abc" 1))
(test "?**" (let ((f (make-string 3 #\*))) (string-set! f 0 #\?) f))
(test #t (string=? "abc" "abc" "abc"))
(test #f (string=? "abc" "abd"))
(test #f (string=? "abc" "ab"))
(test #t (string-ci=? "ABC" "abc" "aBc"))
(test #t (string<? "abc" "abd"))
(test #t (string<? "ab" "abc"))
(test #f (string<? "abc" "abc"))
(test #t (string<? "a" "b" "c"))
(test #t (string>? "b" "a"))
(test #t (string<=? "a" "a" "b"))
(test #t (string>=? "b" "b" "a"))
(test #t (string-ci<? "a" "B"))
(test #t (string-ci>? "B" "a"))
(test #t (string-ci<=? "A" "a"))
(test #t (string-ci>=? "a" "A"))
;; exactly one of <, =, > holds
(test #t (let loop ((pairs '(("a" . "b") ("b" . "a") ("ab" . "ab") ("" . "a") ("Z" . "a"))))
           (or (null? pairs)
               (let ((s (caar pairs)) (t (cdar pairs)))
                 (and (= 1 (length (filter-true (list (string<? s t) (string=? s t) (string>? s t)))))
                      (eq? (string<=? s t) (not (string>? s t)))
                      (eq? (string>=? s t) (not (string<? s t)))
                      (loop (cdr pairs)))))))

(section "6.7 Case conversion")
(test "ABC" (string-upcase "abc"))
(test "abc" (string-downcase "ABC"))
(test "abc" (string-foldcase "ABC"))
(test "STRASSE" (string-upcase "stra\xDF;e"))
(test "strasse" (string-foldcase "Stra\xDF;e"))
(test "a1!" (string-downcase "A1!"))

(section "6.7 substring, append, conversion, copy, fill")
(test "bc" (substring "abcd" 1 3))
(test "" (substring "abc" 1 1))
(test "abc" (substring "abc" 0 3))
(test "abcdef" (string-append "ab" "cd" "ef"))
(test "" (string-append))
(test #f (let ((s "ab")) (eq? s (string-append s))))
(test '(#\a #\b #\c) (string->list "abc"))
(test '(#\b #\c) (string->list "abc" 1))
(test '(#\b) (string->list "abc" 1 2))
(test "abc" (list->string '(#\a #\b #\c)))
(test "" (list->string '()))
(test "bc" (string-copy "abc" 1))
(test "b" (string-copy "abc" 1 2))
(test "abc" (string-copy "abc"))
(test #f (let ((s (make-string 2 #\a))) (eq? s (string-copy s))))
(test "x23" (let ((s (string-copy "123"))) (string-set! s 0 #\x) s))
(define a "12345")
(define b (string-copy "abcde"))
(string-copy! b 1 a 0 2)
(test "a12de" b)
(test "12345" (let ((s (string-copy "abcde"))) (string-copy! s 0 "12345") s))
(test "aabce" (let ((s (string-copy "abcde"))) (string-copy! s 1 s 0 3) s))
(test "bcdde" (let ((s (string-copy "abcde"))) (string-copy! s 0 s 1 4) s))
(test "zzz" (let ((s (make-string 3 #\a))) (string-fill! s #\z) s))
(test "azz" (let ((s (make-string 3 #\a))) (string-fill! s #\z 1) s))
(test "aza" (let ((s (make-string 3 #\a))) (string-fill! s #\z 1 2) s))

(test-report)
